# Generated by Django 3.0.8 on 2020-07-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200715_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='thumbnails',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
